spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hdfc_bank
      username: root
      password: meher
    jpa:
      database: MYSQL
      hibernate:
        ddl-auto: update
      show-sql: true
server:
  port: 3030